<?php
// payfast-ipn.php
// Instant Transaction Notification handler for Bend Cut Send

require __DIR__ . '/config.php'; // assumes $pdo and $payfastPassphrase are defined here

// ===== Helper: simple logger =====
function pf_log($msg)
{
    $file = __DIR__ . '/payfast-ipn.log';
    error_log(date('[Y-m-d H:i:s] ') . $msg . PHP_EOL, 3, $file);
}

// ===== 1. Only accept POST =====
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    pf_log('Invalid method: ' . $_SERVER['REQUEST_METHOD']);
    exit('Method Not Allowed');
}

$postData = $_POST;
pf_log('IPN received: ' . json_encode($postData));

// ===== 2. Signature verification =====
function generateSignature(array $data, string $passphrase): string
{
    if (isset($data['signature'])) {
        unset($data['signature']);
    }

    $pairs = [];
    foreach ($data as $key => $value) {
        if ($value !== '') {
            $pairs[] = $key . '=' . urlencode(trim($value));
        }
    }
    $string = implode('&', $pairs);

    if ($passphrase !== '') {
        $string .= '&passphrase=' . urlencode($passphrase);
    }

    return md5($string);
}

$theirSignature = $postData['signature'] ?? '';
$ourSignature   = generateSignature($postData, $payfastPassphrase);

if ($theirSignature !== $ourSignature) {
    http_response_code(400);
    pf_log('Invalid signature');
    exit('Invalid signature');
}

// ===== 3. Check payment status =====
$status = $postData['payment_status'] ?? '';
if (strcasecmp($status, 'COMPLETE') !== 0) {
    // Not a successful payment, ignore but acknowledge
    http_response_code(200);
    pf_log('Status not COMPLETE: ' . $status);
    exit('Not complete');
}

// ===== 4. Get our quote reference and amount =====
$quoteNumber = $postData['m_payment_id'] ?? '';
$pfAmount    = (float) ($postData['amount_gross'] ?? 0);

if ($quoteNumber === '') {
    http_response_code(400);
    pf_log('Missing m_payment_id');
    exit('Missing quote number');
}

// ===== 5. Look up the quote in DB by quote_number =====
$stmt = $pdo->prepare("SELECT * FROM quotes WHERE quote_number = :qn LIMIT 1");
$stmt->execute([':qn' => $quoteNumber]);
$quote = $stmt->fetch(PDO::FETCH_ASSOC);

if (!$quote) {
    http_response_code(404);
    pf_log('Quote not found: ' . $quoteNumber);
    exit('Quote not found');
}

// ===== 6. Amount check: make sure PayFast amount matches our quote amount =====
$dbAmount = (float) $quote['amount'];

if (abs($dbAmount - $pfAmount) > 0.01) {
    http_response_code(400);
    pf_log("Amount mismatch for {$quoteNumber}: DB {$dbAmount} vs PF {$pfAmount}");
    exit('Amount mismatch');
}

// ===== 7. Everything looks good – mark quote as PAID =====
$update = $pdo->prepare("UPDATE quotes SET status = 'paid' WHERE id = :id");
$update->execute([':id' => $quote['id']]);

pf_log("Quote {$quoteNumber} (id {$quote['id']}) marked as PAID, amount {$pfAmount}");

// ===== 8. Send email notification to you =====

$notifyEmail = 'admin@bendcutsend.net';

$subject = "Payfast payment COMPLETE for quote {$quoteNumber}";
$body    = "A Payfast payment has been completed.\n\n"
         . "Quote number: {$quoteNumber}\n"
         . "Internal ID: {$quote['id']}\n"
         . "Amount paid: R{$pfAmount}\n"
         . "Status: {$status}\n\n"
         . "This message was generated by payfast-ipn.php on bendcutsend.net";

@mail($notifyEmail, $subject, $body);

// ===== 9. Respond OK so PayFast knows we handled it =====
http_response_code(200);
echo 'OK';